name: 'Bump Version and Release'

on:
  # Trigger on demand
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    # Add permissions to the job
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 18

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          target-branch: 'main'
          default: patch
          major-wording: 'MAJOR,major,cut-major,perf'
          minor-wording: 'feat,refactor,improve'
          patch-wording: 'add,Adds,new,icon,change,fix,minor,color,remove,chore,docs,ci,revert,style,test'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.CLEARCI_TOKEN }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CLEARCI_TOKEN }}
        with:
          tag_name: ${{ steps.version-bump.outputs.newTag }}
          release_name: ${{ steps.version-bump.outputs.newTag }}
          draft: false
          prerelease: false

  build-and-publish:
    needs: 'bump-version'
    uses: ClearTax/reusable-workflows/.github/workflows/publish-js-package.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.CLEARCI_TOKEN}}
      github-token: ${{ secrets.CLEARCI_GIT_TOKEN }}
